Automated update

diff --git a/debian_ovpnws b/debian_ovpnws
--- a/debian_ovpnws
+++ b/debian_ovpnws
@@ -506,15 +506,41 @@ echo '{
   "disable_udp": false,
   "obfs": "firenet",
   "auth": {
-    "mode": "passwords",
-    "config": ["firenet1", "firenetdev"]
+    "mode": "external",
+    "config": {
+    "cmd": "./.auth.sh"
+    }
   },
   "recv_window_conn": 107374182400,
   "recv_window_client": 13421772800
 }
 ' >> /etc/hysteria/config.json
 
+echo '{
+#!/bin/bash
+. /etc/openvpn/login/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND is_freeze='0' AND duration > 0"
+username=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$username" != '' ] && [ "$username" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'Authentication failed.'; exit 1
+}
+' >> /etc/hysteria/.auth.sh
+
 chmod 755 /etc/hysteria/config.json
+chmod 755 /etc/hysteria/.auth.sh
 
 sysctl -w net.core.rmem_max=16777216
 sysctl -w net.core.wmem_max=16777216
